exclude_paths:
    - "tests/"
    - "**/vendor/"
engines:
    phpcodesniffer:
        enabled: true
        config:
            file_extensions: "php"
            standard: "PSR1,PSR2"
            ignore_warnings: true
            encoding: utf-8
ratings:
    paths:
        - "**.php"
