services:
    # Inject our custom config manager.
    easyadmin.config.manager:
        class: AdminBundle\Configuration\ConfigManager
        arguments: ['@service_container', '@security.token_storage', '@security.role_hierarchy']

easy_admin:
    site_name: 'Aarhus Events'

    design:
        brand_color: '#154194'
        color_scheme: 'light'
        form_theme: 'horizontal'
        assets:
            css:
                - 'assets/easyadmin.css'

        menu:
            - entity: 'Event'
              icon: 'flag'
              roles: [ROLE_EVENT_EDITOR]
            - entity: 'Place'
              icon: 'map-marker'
              roles: [ROLE_PLACE_EDITOR]
            - entity: 'User'
              icon: 'user-circle-o'
              roles: [ROLE_USER_EDITOR]
            - entity: 'Tag'
              icon: 'tag'
              roles: [ROLE_TAG_EDITOR]
            - entity: 'UnknownTag'
              icon: 'tag'
              roles: [ROLE_TAG_EDITOR]
            - entity: 'Feed'
              roles: [ROLE_FEED_EDITOR]

            - label: 'app.menu.api_docs'
              url: '/api/docs'
              target: '_blank'

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

    list:
        title: '%%entity_label%%'
        max_results: 20
        actions: ['show', 'edit', '-delete']

    entities:
        Event:
            label: app.menu.events
            class: AppBundle\Entity\Event
            list:
                actions:
                    - show
                    - edit
                    - clone
                title: Events
                fields:
                    - property: name
                    - property: isPublished
                      type: boolean
                    - property: image
                      type: image
                    - property: tags
                      label: Tags
                      template: tags.html.twig
                    - property: id
                      sortable: false
                      label: Places
                      template: places.html.twig
                    - property: excerpt
                      label: Excerpt
            form:
                fields:
                    - property: name
                      type_options:
                          required: true
                      help: app.help.event.name
                    - property: isPublished
                    - property: langcode
                      type: choice
                      type_options:
                          choices:
                              '': ''
                              Dansk: da
                              English: en
                              Deutsch: de
                          required: true
                    - property: imageFile
                      type: vich_image
                      type_options:
                          required: true
                      type: url
                    - property: url
                      type: url
                    - property: videoUrl
                    - property: ticketPurchaseUrl
                    - property: excerpt
                      type_options:
                          required: true
                    - property: description
                      type: ckeditor
                      type_options:
                          required: true
                    - property: tags
                      help: 'app.help.event.tags'
                      type: easyadmin_autocomplete
                      type_options:
                          required: true
                          multiple: true
                          class: AppBundle\Entity\Tag
                    - property: occurrences
                      type: collection
                      type_options:
                        entry_type: AdminBundle\Form\OccurrenceType
                        by_reference: false
                      embedded: true

        Occurrence:
            class: AppBundle\Entity\Occurrence
            list:
                label: Occurrence
                fields:
                    - property: startDate
                    - property: endDate
                    - property: place
                    - property: ticketPriceRange
                    - property: eventStatusText

            form:
                fields:
                    - property: startDate
                    - property: endDate
                    - property: place
                      type: easyadmin_autocomplete

        Place:
            label: app.menu.places
            class: AppBundle\Entity\Place
            list:
                title: Places
                fields:
                    - property: name
                    - property: description
                    - property: image
                    - property: url
                    - property: telephone
                    - property: logo
                    - property: langcode
                    - property: video_url
                    - property: disability_access
                    - property: address_country
                    - property: address_locality
                    - property: address_region
                    - property: postal_code
                    - property: street_address
                    - property: latitude
                    - property: longitude
                    - property: email

            form:
                fields:
                    - property: name
                      help: app.help.place.name
                    - property: description
                      help: app.help.place.description
                    - property: street_address
                      type: text
                    - property: postal_code
                      type: text
                    - property: address_locality
                      type: text
                    - property: address_region
                      type: text
                    - property: address_country
                      type: text
                    - property: imageFile
                      type: vich_image
                      # type_options:
                      #   - required: true
                    - property: telephone
                    - property: logo
                    - property: langcode
                    - property: video_url
                    - property: disability_access
                    - property: latitude
                    - property: longitude
                    - property: email

        User:
            label: app.menu.users
            class: AppBundle\Entity\User
            disabled_actions: ['show']
            list:
                fields:
                    - property: username
                    - property: email
                    - property: roles
                      template: roles.html.twig
                    - property: groups
                      template: groups.html.twig
                    - property: enabled
                      type: boolean
                    - lastLogin
            edit:
                fields:
                    - property: enabled
                    - property: username
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              ROLE_API_READ: ROLE_API_READ
                              ROLE_API_WRITE: ROLE_API_WRITE
                              ROLE_EVENT_EDITOR: ROLE_EVENT_EDITOR
                              ROLE_PLACE_EDITOR: ROLE_PLACE_EDITOR
                              ROLE_TAG_EDITOR: ROLE_TAG_EDITOR
                              ROLE_USER_EDITOR: ROLE_USER_EDITOR
                              ROLE_FEED_EDITOR: ROLE_FEED_EDITOR
                              ROLE_ADMIN: ROLE_ADMIN
                    - groups
                    - property: plainPassword
                      type: text
                      type_options:
                          required: false
            new:
                fields:
                    - enabled
                    - username
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              ROLE_API_READ: ROLE_API_READ
                              ROLE_API_WRITE: ROLE_API_WRITE
                              ROLE_EVENT_EDITOR: ROLE_EVENT_EDITOR
                              ROLE_PLACE_EDITOR: ROLE_PLACE_EDITOR
                              ROLE_TAG_EDITOR: ROLE_TAG_EDITOR
                              ROLE_USER_EDITOR: ROLE_USER_EDITOR
                              ROLE_FEED_EDITOR: ROLE_FEED_EDITOR
                              ROLE_ADMIN: ROLE_ADMIN
                    - groups
                    - property: plainPassword
                      type_options:
                          required: true
                      type: text
                      type_options:
                          required: false

        Tag:
            label: app.menu.tags
            class: AppBundle\Entity\Tag
            list:
                fields:
                    - property: name
            show:
                fields:
                    - property: name
            form:
                fields:
                    - property: name

        UnknownTag:
            label: app.menu.unknown_tags
            class: AppBundle\Entity\UnknownTag
            list:
                fields:
                    - property: name
                    - property: tag
            form:
                fields:
                    - property: name
                    - property: tag

        Feed:
            label: app.menu.feeds
            class: AdminBundle\Entity\Feed
            list:
                fields:
                    - property: name
                    - property: url
                      type: url
                    - property: lastRead

            form:
                fields:
                    - property: name
                    # - property: configuration
                    #   type: text

vich_uploader:
    db_driver: orm
    mappings:
        thing_images:
            upload_destination: "%admin.uploads_path%"
            uri_prefix:         "%admin.uploads_url%"
