app:
    resource: '@AdminBundle/Action/'
    type:     'annotation'

api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'

# doc:
#     resource: '@ApiPlatformBundle/Resources/config/routing/swagger-ui.xml'

api_login_check:
    path: '/api/login_check'

admin:
  resource: '@AdminBundle/Controller/'
  type:     'annotation'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

ResqueBundle:
    resource: "@ResqueBundle/Resources/config/routing.xml"
    prefix:   /resque

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /easyadmin