# Example config file for the Schema Generator
# Use the following command to regenerate entities:
# bin/schema generate-types src/ app/config/schema.yml

types:
  # https://schema.org/Event
  Event:
    properties:
      startDate: ~
      endDate: ~

  # Parent class of Event
  Thing:
    properties:
      name: ~
      description: ~
      image: ~
      url: ~

namespaces:
  entity: AppBundle\Entity

annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ApiPlatformCoreAnnotationGenerator
