# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    resource.event.order_filter:
        parent:    "api_platform.doctrine.orm.order_filter"
        arguments: [ { occurrences.startDate: ~, occurrences.endDate: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'event.order' } ]

    resource.event.search_filter:
        parent:    "api_platform.doctrine.orm.search_filter"
        arguments: [ { name: "partial", description: "partial" } ]
        tags:      [ { name: 'api_platform.filter', id: 'event.search' } ]

    resource.event.search_date_filter:
        parent:    "api_platform.doctrine.orm.date_filter"
        arguments: [ { occurrences.startDate: ~, occurrences.endDate: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'event.search.date' } ]

    app_bundle.doctrine.orm.tag_filter:
        class:      AppBundle\Filter\TagFilter
        arguments:  [ "@doctrine", "@request_stack", "@fpn_tag.tag_manager" ]
        public:     false

    resource.event.search_tag_filter:
        parent:    "app_bundle.doctrine.orm.tag_filter"
        arguments: [ 'tags' ]
        tags:      [ { name: 'api_platform.filter', id: 'event.search.tag' } ]

    resource.occurrence.order_filter:
        parent:    "api_platform.doctrine.orm.order_filter"
        arguments: [ { startDate: ~, endDate: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'occurrence.order' } ]

    resource.occurrence.search_date_filter:
        parent:    "api_platform.doctrine.orm.date_filter"
        arguments: [ { startDate: ~, endDate: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'occurrence.search.date' } ]

    # https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2048
    fos_user.doctrine_registry:
        alias: doctrine

    security.access.event_voter:
        class:      AppBundle\Security\Authorization\Voter\EventVoter
        public:     false
        tags:
            - { name: security.voter }

    # https://api-platform.com/doc/1.0/api-bundle/the-event-system
    event.event_listener:
        class: AppBundle\EventListener\EventListener
        arguments: [ "@service_container" ]
        tags:
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }

    feed_reader.json:
        class: AdminBundle\Service\FeedReader\Json

    feed_reader.xml:
        class: AdminBundle\Service\FeedReader\Xml

    twig_extension:
        class: AdminBundle\Twig\Extension\TwigExtension
        tags:
            - { name: "twig.extension" }

    # Override vendor/api-platform/core/src/Bridge/Symfony/Bundle/Resources/config/jsonld.xml
    api_platform.jsonld.normalizer.item:
        public: false
        class: AppBundle\Serializer\CustomItemNormalizer
        arguments:
            - "@api_platform.metadata.resource.metadata_factory"
            - "@api_platform.metadata.property.name_collection_factory"
            - "@api_platform.metadata.property.metadata_factory"
            - "@api_platform.iri_converter"
            - "@api_platform.resource_class_resolver"
            - "@api_platform.jsonld.context_builder"
            - "@api_platform.property_accessor"
            - "@?api_platform.name_converter"
            - "@fpn_tag.tag_manager"
        tags: [ { name: serializer.normalizer, priority: 10 } ]
