# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    resource.event.order_filter:
        parent:    "api_platform.doctrine.orm.order_filter"
        arguments: [ { occurrences.startDate: ~, occurrences.endDate: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'event.order' } ]

    resource.event.search_filter:
        parent:    "api_platform.doctrine.orm.search_filter"
        arguments: [ { name: "partial", description: "partial" } ]
        tags:      [ { name: 'api_platform.filter', id: 'event.search' } ]

    resource.event.search_date_filter:
        parent:    "api_platform.doctrine.orm.date_filter"
        arguments: [ { occurrences.startDate: ~, occurrences.endDate: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'event.search.date' } ]

    # https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2048
    fos_user.doctrine_registry:
        alias: doctrine

    security.access.event_voter:
        class:      AppBundle\Security\Authorization\Voter\EventVoter
        public:     false
        tags:
            - { name: security.voter }

    # https://api-platform.com/doc/1.0/api-bundle/the-event-system
    event.event_listener:
        class: AppBundle\EventListener\EventListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: api.pre_update, method: onPreUpdate }
            - { name: kernel.event_listener, event: api.pre_delete, method: onPreDelete }

    feed_reader.json:
        class: AdminBundle\Service\FeedReader\Json

    feed_reader.xml:
        class: AdminBundle\Service\FeedReader\Xml
