# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

# Examples of API resource mapping, learn more at
# https://github.com/dunglas/DunglasApiBundle

    resource.event.order_filter:
        parent:    "api.doctrine.orm.order_filter"
        arguments: [ { "startDate": ~, "endDate": ~ } ]

    resource.event.search_filter:
        parent:    "api.doctrine.orm.search_filter"
        arguments: [ { name: "partial", description: "partial" } ]

    resource.event.date_filter:
        parent:    "api.doctrine.orm.date_filter"
        arguments: [ { startDate: ~, endDate: ~ } ]

    resource.event:
        parent:      "api.resource"
        arguments: [ "AppBundle\\Entity\\Event" ]
        calls:
            - method:    "initFilters"
              arguments: [ [ "@resource.event.order_filter", "@resource.event.search_filter", "@resource.event.date_filter" ] ]
        tags:      [ { name: "api.resource" } ]
