# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    value_converter:
        class: AdminBundle\Service\FeedReader\ValueConverter

    # Factories
    entity_factory:
        class: AdminBundle\Factory\EntityFactory
        abstract:  true
        arguments: [ "@service_container", "@doctrine.orm.entity_manager", "@value_converter", "@fpn_tag.tag_manager" ]

    place_factory:
        parent: entity_factory
        class: AdminBundle\Factory\PlaceFactory

    occurrence_factory:
        parent: entity_factory
        class: AdminBundle\Factory\OccurrenceFactory
        calls:
            - [setPlaceFactory, ["@place_factory"]]

    event_factory:
        parent: entity_factory
        class: AdminBundle\Factory\EventFactory
        calls:
            - [setOccurrenceFactory, ["@occurrence_factory"]]

    # Filters
    resource.event.order_filter:
        parent:    "api_platform.doctrine.orm.order_filter"
        arguments: [ { occurrences.startDate: ~, occurrences.endDate: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'event.order' } ]

    resource.event.search_filter:
        parent:    "api_platform.doctrine.orm.search_filter"
        arguments: [ { name: "partial", description: "partial", langcode: "exact", occurrences.place.name: "partial" } ]
        tags:      [ { name: 'api_platform.filter', id: 'event.search' } ]

    resource.event.search_date_filter:
        parent:    "api_platform.doctrine.orm.date_filter"
        arguments: [ { occurrences.startDate: ~, occurrences.endDate: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'event.search.date' } ]

    app_bundle.doctrine.orm.tag_filter:
        class:      AppBundle\Filter\TagFilter
        arguments:  [ "@doctrine", "@request_stack", "@fpn_tag.tag_manager" ]
        public:     false

    resource.event.search_tag_filter:
        parent:    "app_bundle.doctrine.orm.tag_filter"
        arguments: [ 'tags' ]
        tags:      [ { name: 'api_platform.filter', id: 'event.search.tag' } ]

    resource.occurrence.order_filter:
        parent:    "api_platform.doctrine.orm.order_filter"
        arguments: [ { startDate: ~, endDate: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'occurrence.order' } ]

    resource.occurrence.search_date_filter:
        parent:    "api_platform.doctrine.orm.date_filter"
        arguments: [ { startDate: ~, endDate: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'occurrence.search.date' } ]

    # https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2048
    fos_user.doctrine_registry:
        alias: doctrine

    security.access.event_voter:
        class:      AppBundle\Security\Authorization\Voter\EventVoter
        public:     false
        arguments: [ "@?security.role_hierarchy" ]
        tags:
            - { name: security.voter }

    # https://api-platform.com/doc/1.0/api-bundle/the-event-system
    event.event_listener:
        class: AppBundle\EventListener\EventListener
        arguments: [ "@service_container" ]
        tags:
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }

    feed_reader.json:
        class: AdminBundle\Service\FeedReader\JsonPath

    feed_reader.xml:
        class: AdminBundle\Service\FeedReader\Xml

    feed_reader_event_importer:
        class: AdminBundle\Service\FeedReader\EventImporter
        arguments:
            - "@event_factory"
            - "@place_factory"
            -
                base_url: "%admin.base_url%"
                images:
                    path: "%admin.images_path%"
                    url: "%admin.images_url%"

    feed_reader:
        class: AdminBundle\Service\FeedReader
        arguments:
            - "@value_converter"
            - "@feed_reader_event_importer"
            -
                readers:
                    json: "@feed_reader.json"
                    xml: "@feed_reader.xml"
            - "@logger"
            - "@security.token_storage"
            - "@stof_doctrine_extensions.listener.blameable"

    twig_extension:
        class: AdminBundle\Twig\Extension\TwigExtension
        tags:
            - { name: "twig.extension" }

    # Override vendor/api-platform/core/src/Bridge/Symfony/Bundle/Resources/config/jsonld.xml
    api_platform.jsonld.normalizer.item:
        public: false
        class: AppBundle\Serializer\CustomItemNormalizer
        arguments:
            - "@api_platform.metadata.resource.metadata_factory"
            - "@api_platform.metadata.property.name_collection_factory"
            - "@api_platform.metadata.property.metadata_factory"
            - "@api_platform.iri_converter"
            - "@api_platform.resource_class_resolver"
            - "@api_platform.jsonld.context_builder"
            - "@api_platform.property_accessor"
            - "@?api_platform.name_converter"
            - "@fpn_tag.tag_manager"
            - "@place_factory"
        tags: [ { name: serializer.normalizer, priority: 10 } ]
